### ISSUE TITLE
404: Not found of time_series_19-covid-Recovered.csv

### ISSUE THREAD

**Issue by fireb86** [aleskandro/covid19-charts-spreading-rapidity#3]
the call https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Recovered.csv return 404

**Comment by aleskandro** [comment]
Hi @fireb86, thank you, new build is queued in the docker hub ci pipeline and fix will be available in production in a few minutes. However, the problem is related to the lack of good "recovered" data worldwide; the team at CSSEGISandData has deleted that file and it will be no available anymore. I just changed the url to point to the file in a old commit. When I will have time I'll try to fix better because I would like to maintain at least for Italy the recovered charts.
